mensaje = raw_input("introduzca mensaje a ecriptar: ")
clave = raw_input("introduzca palabra clave: ")
n = len(mensaje)    #cuento la cantidad de caracteres
posicion= 0
ab=clave[0]
index = abc.index(ab)
encoding = ""
suma = 0
espacios= ""
espacios=espacios(mensaje)

for x in espacios
    for y in range(rpas):
    	li = 0
    	    if x==abc[y]:
    	        li=y+index
    	        if li <= rpas
    	            encoding =encondig+abc[li]

    	            else        :
    	                suma= restar(rpas, li)
    	                encodigo =encodigo+abc[suma]+ "$"
    	                suma = 0
#print encoding
print "mensaje cifrado: ",invertir(encondig)
print "su clave es:", clave    	                
